Fix/sync connection frequency tooling
NangoHQ/nango pull request #1549
Opened 2024-01-23 14:02 UTC by bodinsamuel

Follow up of #1548

## Describe your changes

- Update node-client
- Update open api
- Update documentation

2024-01-23 18:48 UTC, khaliqgant requested changes
Looks good. [Node client documentation](https://docs.nango.dev/sdks/node) should be updated as well at https://github.com/NangoHQ/nango/blob/master/docs-v2/sdks/node.mdx

2024-01-24 08:04 UTC, bodinsamuel commented
Oh good call, I didn't noticed there was a doc for the client thanks 👍🏻

2024-01-24 14:29 UTC, bodinsamuel commented
Is this good for you @khaliqgant ? ☺️

2024-01-24 14:38 UTC, khaliqgant requested changes
Can you remove the whitespace changes in `[docs-v2/sdks/node.mdx](https://github.com/NangoHQ/nango/pull/1549/files#diff-202fbe3f1a0f65d56a97c3bf855140eb2c2f504e6e519589aadcfb9cff656d3e)`? That file is sensitive in how the layout should be so the whitespace there is intentional. The only diff there should be the content you added at the bottom

2024-01-24 15:03 UTC, bodinsamuel commented
Understood, I think those are only whitespaces at the end of the lines. 
They don't change the layout as far as I noticed, it's just git (with `git config core.whitespace fix`) and the default vscode linter that removes them.

![Screenshot 2024-01-24 at 15 55 36](https://github.com/NangoHQ/nango/assets/1637651/afcb81d7-bb24-4bde-a5c2-cd9d351277c4)


edit: After checking locally
The only place where it was indeed not good after trimming, was `**Return value**` but it should be a heading anyway. So I added a line-break

2024-01-24 15:17 UTC, bastienbeurier commented on docs-v2/sdks/node.mdx
> +### Update sync's connection frequency
I would rephrase to: 
"Override a sync's frequency for a specific connection"

2024-01-24 15:17 UTC, bastienbeurier commented on docs-v2/sdks/node.mdx
> +To update a sync's connection frequency, or revert to the default frequency:
Same here: "To override a sync's frequency for a specific connection, or revert to the default frequency, us:"

2024-01-26 15:44 UTC, TBonnin commented
@khaliqgant I removed the whitespace changes in node.mdx

2024-01-26 17:33 UTC, khaliqgant approved these changes

2024-01-26 17:33 UTC, merged