Contribute to Tiktok Accounts API
NangoHQ/nango pull request #1591
Opened 2024-01-31 21:30 UTC by jason-novo

2024-02-02 19:38 UTC, bastienbeurier commented
Sorry for the delay here @jason-novo. Reviewing now.

2024-02-02 19:39 UTC, bastienbeurier requested changes

2024-02-02 19:39 UTC, bastienbeurier commented on docs-v2/integrations/all/tiktok-accounts.mdx
> +---
You need to add this page to the mint.json file, otherwise it won't show up.

2024-02-14 10:39 UTC, khaliqgant commented
Closing in favor of https://github.com/NangoHQ/nango/pull/1672 which adds the mint.json

2024-02-14 10:39 UTC, closed without merging