Fix edit frequency
NangoHQ/nango pull request #1852
Opened 2024-03-14 10:06 UTC by hassan254-prog

## Describe your changes
Display frequency whenever the user clicks on Edit
![frequency_edit](https://github.com/NangoHQ/nango/assets/85742599/a5e9c4b6-15c1-42cc-826f-a6a7cdf3d59b)

2024-03-14 10:33 UTC, khaliqgant requested changes
Thanks. The "every" should show when showing an existing frequency

"hour" by itself doesn't make sense.

Also just noticed this issue, "hours" is still accepted and is a confusing unit "every hours"


https://github.com/NangoHQ/nango/assets/1724137/5ba0fc5d-68d1-4565-b932-ca32436e76c6

2024-03-14 10:35 UTC, bodinsamuel approved these changes
Works great, minor comments

2024-03-14 10:35 UTC, bodinsamuel commented on packages/webapp/src/pages/Integration/FlowPage.tsx
> +    const onCancelFrequncy = () => {
```suggestion
    const onCancelFrequency = () => {
```

2024-03-14 10:35 UTC, bodinsamuel commented on packages/webapp/src/pages/Integration/FlowPage.tsx
> +                                                onClick={() => onCancelFrequncy()}
```suggestion
                                                onClick={() => onCancelFrequency()}
```

2024-03-18 10:24 UTC, hassan254-prog commented
@khaliqgant , I have just updated my PR, to check for time units such as "every hours", "every days", "every mins" . It was also accepting "every mins" as an input which is a value less than 5 for minutes.

2024-03-19 13:01 UTC, bodinsamuel reviewed
I think the change requested by Khaliq were unrelated to this PR and it has introduced bugs unfortunately.
- Adding a space before `every` will add an other every
- Adding a space between `every` and `hours` make the cursor jump to the end
- Saving `every hours` complains about the missing unit and revert the input value

2024-05-30 06:23 UTC, closed without merging