Add Support for Microsoft Ads API
NangoHQ/nango pull request #1969
Opened 2024-04-10 03:25 UTC by matthewbelair

## Describe your changes

- Added configuration for microsoft-ads in providers.yaml
- Added microsoft-ads to docs-v2.
- Added microsoft-ads pages for Pre-Configured APIs group in mint.json.
- Consolidate microsoft-ads docs pages

## Test

This provider has been used successfully in local development to connect to Microsoft Ads and successfully call those endpoints after authorizing using Nango.

The documentation update was reviewed using npm run docs and verifying on localhost.

## Issue ticket number and link

Related to [this thread](https://nango-community.slack.com/archives/C04ABR352H0/p1712349133436789) in the Slack channel.

2024-04-19 03:19 UTC, TBonnin reviewed
Thank you @matthewbelair It should probably be added to https://github.com/NangoHQ/nango/blob/2e9d5e7e52ffc4ef81988dd94661538fc31b0e32/docs-v2/integrations/marketing.mdx?plain=1#L9

2024-05-01 19:50 UTC, matthewbelair commented
@TBonnin sure, done. Any timeline for when this can be merged? Thanks

2024-05-01 19:59 UTC, TBonnin commented
> @TBonnin sure, done. Any timeline for when this can be merged? Thanks

Can you rebase your branch? Then I will merge it before the end of the day

2024-05-01 21:38 UTC, TBonnin requested changes

2024-05-01 21:38 UTC, TBonnin commented on packages/shared/providers.yaml
> +    proxy: null
`proxy: null` is not allowed actually. Just remove this line, then the proxy value of the aliased provider will be used

2024-05-03 13:56 UTC, matthewbelair commented
@TBonnin should be good now. Thanks!

2024-05-03 14:33 UTC, merged