fix(api): stop using env cookie
NangoHQ/nango pull request #1987
Opened 2024-04-15 08:42 UTC by bodinsamuel

## Describe your changes

Fixes NAN-729

2024-04-15 18:17 UTC, khaliqgant requested changes
Trying to create a connection results in 
![image](https://github.com/NangoHQ/nango/assets/1724137/30113e26-c873-4589-bf24-23c929c733c6)

2024-04-15 20:08 UTC, bodinsamuel commented
> Looks like the frontend sdk calls need to set an env as well.

There is a deeper issue here, because it shouldn't be the case. There is some shared code that shouldn't shared across different auth strategy

2024-04-16 15:16 UTC, bodinsamuel commented
Can I get a review again? @khaliqgant @TBonnin

2024-04-17 01:11 UTC, TBonnin approved these changes

2024-04-17 01:11 UTC, TBonnin commented on packages/server/lib/utils/utils.ts
> +    if (!getUser.ok) {
maybe we should agree on an unique way to check for failure. For example always using `isErr` or `isOk`. I think the consistency will make code easier to read on the long term

2024-04-17 07:56 UTC, bodinsamuel commented on packages/server/lib/utils/utils.ts
> +    if (!getUser.ok) {
ah yeah, it just works like this so I don't always think about the helpers

2024-04-17 08:42 UTC, khaliqgant approved these changes
Code looks good. I haven’t had a chance to pull again locally to test but feel free to merge if you want. If not I’ll test again this evening

2024-04-17 08:42 UTC, bodinsamuel commented on packages/server/lib/utils/utils.ts
> +    if (!getUser.ok) {
Fixed*

2024-04-17 08:42 UTC, merged