feat(integrations): add support for productboard
NangoHQ/nango pull request #2194
Opened 2024-05-22 21:46 UTC by hassan254-prog

## Describe your changes

- Added configuration for productboard in providers.yaml
- Added productboard to docs-v2.
- Added productboard pages for Supported API groups in mint.json.
- Added productboard SVG file in template-logos folder.
- Consolidate productboard docs pages

## Issue ticket number and link
[EXT-70](https://linear.app/nango/issue/EXT-70/add-productboard-api)
## Test
This provider has been used successfully in local development to connect to productboard after authorizing using Nango.
The documentation update was reviewed using `npm run docs` and verifying on localhost.

2024-05-23 07:49 UTC, bodinsamuel reviewed
📈

2024-05-23 07:49 UTC, bodinsamuel commented on docs-v2/integrations/all/productboard.mdx
> +-   [How Register an Application](https://developer.productboard.com/docs/how-to-integrate-with-productboard-via-oauth2-developer-documentation#registering-an-oauth2-application)
```suggestion
-   [How to Register an Application](https://developer.productboard.com/docs/how-to-integrate-with-productboard-via-oauth2-developer-documentation#registering-an-oauth2-application)
```

2024-05-23 07:49 UTC, bodinsamuel commented on docs-v2/integrations/all/productboard.mdx
> +-   [OAuth-related docs](https://developer.productboard.com/docs/how-to-integrate-with-productboard-via-oauth2-developer-documentation)
```suggestion
-   [OAuth related docs](https://developer.productboard.com/docs/how-to-integrate-with-productboard-via-oauth2-developer-documentation)
```

2024-05-23 07:49 UTC, bodinsamuel commented on docs-v2/integrations/all/productboard.mdx
> +-   [Productboard API docs (their REST API)](https://developer.productboard.com/reference/introduction)
```suggestion
-   [Productboard REST API docs](https://developer.productboard.com/reference/introduction)
```

2024-05-23 23:02 UTC, hassan254-prog commented
@bodinsamuel thank you for catching that 🙏

2024-05-24 08:31 UTC, bodinsamuel approved these changes

2024-05-24 11:57 UTC, khaliqgant approved these changes

2024-05-24 11:58 UTC, khaliqgant commented on packages/shared/providers.yaml
> +            X-Version: 1
Can we make this a "1" (string) so yaml validation passes?

2024-05-24 11:58 UTC, khaliqgant requested changes
Small configuration change requested

2024-05-24 20:05 UTC, hassan254-prog commented on packages/shared/providers.yaml
> +            X-Version: 1
@khaliqgant, thanks for catching that. 🙏

2024-05-27 07:40 UTC, bodinsamuel approved these changes

2024-05-27 08:17 UTC, merged