fix(oauth2_cc): accommodate expires_in for fiserv
NangoHQ/nango pull request #2574
Opened 2024-07-31 22:25 UTC by hassan254-prog

## Describe your changes
Fiserv returns `expires_in` in milliseconds, small follow up from [2573](https://github.com/NangoHQ/nango/pull/2573)
## Issue ticket number and link
[EXT-111](https://linear.app/nango/issue/EXT-111/add-support-for-fiserv)

2024-08-01 08:40 UTC, TBonnin commented on packages/shared/lib/services/connection.service.ts
> +                    expiresAt = new Date(Date.now() + (provider === 'fiserv' ? expiresIn : expiresIn * 1000));
not a huge fan of making our codebase more complex to handle a bug from a provider. The oauth RFC clearly indicates that expires_in should be in seconds https://www.rfc-editor.org/rfc/rfc6749#section-4.2.2

2024-08-01 09:53 UTC, hassan254-prog commented on packages/shared/lib/services/connection.service.ts
> +                    expiresAt = new Date(Date.now() + (provider === 'fiserv' ? expiresIn : expiresIn * 1000));
I was also against this. As we see more and more custom flows, perhaps in the future we could have a separate package that handles only custom flows, thereby maintaining a clean codebase.

2024-08-01 15:10 UTC, khaliqgant commented on packages/shared/lib/services/connection.service.ts
> +                    expiresAt = new Date(Date.now() + (provider === 'fiserv' ? expiresIn : expiresIn * 1000));
Could this be abstracted into the yaml maybe and override the default there?

2024-08-02 15:06 UTC, hassan254-prog commented on packages/shared/lib/services/connection.service.ts
> +                    expiresAt = new Date(Date.now() + (provider === 'fiserv' ? expiresIn : expiresIn * 1000));
@khaliqgant , thank you for this cleaner approach. I have updated my PR with this [commit](https://github.com/NangoHQ/nango/pull/2574/commits/d06b792b3189da98ea69732cc739be811dce8871)

2024-08-02 15:43 UTC, khaliqgant requested changes
Validation needs to be updated as well https://github.com/NangoHQ/nango/tree/master/scripts/validation/providers

2024-08-02 16:09 UTC, hassan254-prog commented
Thanks @khaliqgant for catching this, I have updated in this [commit](https://github.com/NangoHQ/nango/pull/2574/commits/c2cdc638af41bed78328f980f0c10336d7a8e465)

2024-08-02 16:16 UTC, khaliqgant approved these changes

2024-08-05 08:33 UTC, bodinsamuel approved these changes

2024-08-05 08:40 UTC, merged