Add demo video to docs and readme
NangoHQ/nango pull request #2950
Opened 2024-11-06 15:48 UTC by bastienbeurier

2024-11-06 16:02 UTC, bodinsamuel approved these changes

2024-11-06 16:04 UTC, TBonnin commented on docs-v2/images/overview.png
this image and the one below are half a meg each.

2024-11-06 16:04 UTC, TBonnin requested changes
Images are way too big imho

2024-11-07 07:47 UTC, bastienbeurier commented
> Images are way too big imho

Agreed, I'll lower the res

2024-11-07 07:59 UTC, bastienbeurier commented
> Images are way too big imho

Done!

2024-11-07 14:20 UTC, TBonnin approved these changes

2024-11-07 16:02 UTC, merged