feat(copper): integration
NangoHQ/nango pull request #3071
Opened 2024-11-27 14:22 UTC by dannylwe

2024-11-29 10:34 UTC, bodinsamuel approved these changes

2024-11-29 11:28 UTC, khaliqgant commented on docs-v2/integrations/all/copper.mdx
> +- Copper offers both OAuth and API_KEY authentication modes. To use OAuth2.0 with Copper, you must first register your application.
Shouldn't we also add support for the API key auth as well?

2024-11-29 11:28 UTC, khaliqgant commented on docs-v2/integrations/all/copper.mdx
> +- The Dev API uses token based authentication. You have to include the token in the header of every request, along with the email address of the user who generated the token.
@dannylwe where in their documentation is this specified? Shouldn't we inject this for the user if this is the case?

2024-11-29 11:39 UTC, hassan254-prog commented on packages/shared/providers.yaml
> +    docs: https://docs.nango.dev/integrations/all/copper
It might be helpful to include the docs link at the end.

2024-11-29 11:40 UTC, hassan254-prog commented
@khaliqgant, should we also start documenting for `connect-ui` now to prevent the need to backfill these docs in the future?

2024-11-29 11:41 UTC, khaliqgant commented
> @khaliqgant, should we also start documenting for `connect-ui` now to prevent the need to backfill these docs in the future?

Yes, absolutely. Thanks for bringing this up.

2024-11-29 13:02 UTC, dannylwe commented on docs-v2/integrations/all/copper.mdx
> +- The Dev API uses token based authentication. You have to include the token in the header of every request, along with the email address of the user who generated the token.
@khaliqgant Makes sense. This should be injected for the user

2024-11-29 14:10 UTC, khaliqgant requested changes
Changes requested inline

2024-11-29 17:16 UTC, dannylwe commented on docs-v2/integrations/all/copper.mdx
> +- Copper offers both OAuth and API_KEY authentication modes. To use OAuth2.0 with Copper, you must first register your application.
This has been added

2024-11-29 17:29 UTC, hassan254-prog approved these changes

2024-12-02 09:10 UTC, bodinsamuel commented
is it okay to merge?

2024-12-02 09:13 UTC, khaliqgant commented on docs-v2/integrations/all/copper.mdx
> +  Guide to connect to Asana-Scim using Nango Connect.
```suggestion
  Guide to connect to Copper API Key using Nango Connect.
```

2024-12-02 09:14 UTC, khaliqgant approved these changes

2024-12-02 09:22 UTC, merged