feat(integrations): add support for BuiltWith
NangoHQ/nango pull request #3220
Opened 2024-12-23 15:41 UTC by gkhngyk

What is BuiltWith ?
[BuiltWith®](https://builtwith.com) is a website profiler, lead generation, competitive analysis and business intelligence tool providing technology adoption, ecommerce data and usage analytics for the internet.

BuiltWith technology tracking includes widgets, analytics, frameworks, content management systems, advertisers, content delivery networks, web standards and web servers to name some of the technology categories covered.

2024-12-24 15:53 UTC, hassan254-prog reviewed
Thanks @gkhngyk for the contribution, small comments inline otherwise LGTM 💪

2024-12-24 15:53 UTC, hassan254-prog commented on packages/shared/providers.yaml
> +            example: 1bc32cba-a5d6-438a-bbcc-af312f560a3c
You could also add the pattern here, using your example, you could use 
`format: uuid`

2024-12-24 15:53 UTC, hassan254-prog commented on packages/shared/providers.yaml
> +            example: 1bc32cba-a5d6-438a-bbcc-af312f560a3c
Also prepared a template logo you could [use](https://codefile.io/f/Px3RIYNx5v)

2024-12-24 15:53 UTC, hassan254-prog commented on packages/shared/providers.yaml
> +            example: 1bc32cba-a5d6-438a-bbcc-af312f560a3c
Could you please also add the `connect-ui` documentation? You may refer to the following [example](https://github.com/NangoHQ/nango/pull/3121/files#diff-db1f0aeac4811ed0b6ff9e1b043d645fee90550bbf0b123b70541e8d8ec6cca6).

2024-12-25 15:19 UTC, gkhngyk commented on packages/shared/providers.yaml
> +            example: 1bc32cba-a5d6-438a-bbcc-af312f560a3c
@hassan254-prog  Can you help me solve the above problem

2024-12-25 20:39 UTC, gkhngyk commented
@hassan254-prog  i solve all issues. Can you check again?

2024-12-26 10:12 UTC, khaliqgant commented on docs-v2/integrations/all/builtwith.mdx
> +- [Generate a BuiltWith API key in your BuiltWith account](https://api.builtwith.com)
```suggestion
- [Generate a BuiltWith API key in your BuiltWith account](https://api.builtwith.com)
- [BuiltWith API Docs](https://api.builtwith.com/free-api)
```

2024-12-26 10:14 UTC, khaliqgant commented on packages/shared/providers.yaml
> +            format: uuid
```suggestion
            format: uuid
            doc_section: '#step-1-finding-your-api-key'
```

2024-12-26 10:15 UTC, khaliqgant requested changes
Looks great, thanks for your contribution! Couple of small suggestions to make this complete 😀

2024-12-26 11:20 UTC, khaliqgant approved these changes

2024-12-27 08:43 UTC, merged