Api Feature add param refresh_token -> option to not include refresh token in response
NangoHQ/nango pull request #650
Opened 2023-05-30 08:59 UTC by bramkn

Issue: https://github.com/NangoHQ/nango/issues/643

After conversation with @bastienbeurier added the parameter as he suggested.
This would be a "breaking change" as it would result people that use the refresh token itself to not have this available anymore as the default value is set to false making the refresh token not be sent anymore.

2023-05-30 16:07 UTC, khaliqgant commented
Awesome, thanks for your contribution @bramkn! 

Can you fix the few build errors as seen here: https://github.com/NangoHQ/nango/actions/runs/5119559879/jobs/9204979767?pr=650

They can also be seen [inline](https://github.com/NangoHQ/nango/pull/650/files#diff-e24662cdfc666bf649e1374659ec209bbb0859fa39e116aed413962fee01dbecR260)

![image](https://github.com/NangoHQ/nango/assets/1724137/b354084a-1e4a-447d-82b8-030077542595)

as well.

Thanks!

2023-05-30 16:08 UTC, khaliqgant requested changes
See comment: https://github.com/NangoHQ/nango/pull/650#issuecomment-1568702787 😃

2023-06-06 08:10 UTC, bramkn commented
@khaliqgant Please have a look, it should now all be changed.

2023-06-06 08:11 UTC, khaliqgant commented
Ok thanks, will take a look today!

2023-06-06 18:40 UTC, khaliqgant approved these changes

2023-06-06 18:40 UTC, khaliqgant commented
cc/ @rguldener we'll need to document this update.

2023-06-06 18:40 UTC, merged